const DISTRACTED_UPDATE_SECONDS = 5
const NO_LIMIT = -1;
const OUR_APP_SINGLE_SESSION_PREFIX = "!*"
const DISTRACTED_DOMAIN = ":}";
// const LIMIT_EXCEEDED_TYPE_CONTINUOUS = 3;
// const LIMIT_EXCEEDED_TYPE_OVERALL = 4;
const LIMIT_EXCEEDED_TYPE_CONTINUOUS = 0.1;
const LIMIT_EXCEEDED_TYPE_OVERALL = 0.1;
